# Reading in data files and inspecting the resulting dataframe

### Okay, we have some data and we would like to inspect it, wrangle it, and analyze it.
### It of course all starts with getting the data in your pandas dataframe.

### There are many ways to get data into pandas, most have the following syntax:
- `pd.read_csv()`
- `pd.read_excel()`
- `pd.read_parquet()`
- `pd.read_sql()`
- etc. etc.

### See this link for more options:
https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

### But first, let's start with importing pandas

In [1]:
import pandas as pd

### We check which files are available in the directory with a magic command `%ls`:

In [2]:
%ls

sample_data/

### Let's read in some data with `pd.read_csv()`. It's common practice to assign the result to a variable called `df`

In [3]:
df = pd.read_csv('https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/titanic.csv')

### What did we just create here? We can use the general python function `type()` to get info what type of object this is:

In [4]:
type(df)

pandas.core.frame.DataFrame

### Let's see what we got when we did this and inspect the first lines with `df.head()`. This is a method that is available on dataframes and series.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Or check the last lines with `df.tail()`

In [6]:
df.tail(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

### What is the shape of this dataframe? We can use the attribute `.shape`

In [7]:
df.shape

(891, 15)

### What are the names of all columns? We can see that with another attribute called `.columns`

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [9]:
type(df.columns)

pandas.core.indexes.base.Index

### As you can see pandas calls this an Index (which contains all column names)

### And while we're at it, let's also check the index of this dataframe with the attribute .index

In [ ]:
df.index

### DataFrames have many methods and attributes, you can check them with tab completion

In [ ]:
df.

### Let's see what the dataframe looks like in general by using dataframe method `.info()`

In [ ]:
df.info()

### Reading in data with `pd.read_csv()` went very easy (maybe too easy?). Let's check what arguments are available for this function, using `Shift + Tab` inside the function.

In [ ]:
pd.read_csv()

### Can we maybe get a short numerical summary of the data? Yes, we can, with: `df.describe()`

In [ ]:
df.describe(include='all')

### To get quick info about a column of the counts we can do `df['column_name'].value_counts(dropna=False)`

In [ ]:
df['sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

## New concepts discussed here:
- general pandas methods: `pd.read_csv()`
- attributes of dataframes, such as: `df.shape`, `df.columns`
- and methods of a dataframe: `df.head()`, `df.info()`, `df.describe()`
- get counts of values in a column: df['column_name'].value_counts()