# Trying basic manipulations on movies yourself

## 1) import pandas and read in the movie dataset (`'https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv'`) and assign to a variable df

In [82]:
import pandas as pd
df = pd.read_csv('https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv')
#df.head(5)

## 2) Run the following line to make sure you can see all the columns of your dataframe

In [70]:
pd.options.display.max_columns = 100

## 3) Check the first few lines of your dataframe

In [71]:
#df.head(5)

## 4) Get the summary statistics of your dataframe using `.describe()`. What is the mean averageRating and what is the max averageRating for the movies?

In [72]:
df.describe()
#averageRating is 6.87
#max averageRating is 9.5

,isAdult,startYear,endYear,runtimeMinutes,averageRating,numVotes,metascore
count,5830.0,5830.000000,435.000000,5827.000000,5830.000000,5.830000e+03,4816.00000
mean,0.0,2002.390051,2011.032184,104.589326,6.873945,1.297261e+05,58.83015
std,0.0,15.344028,9.370946,30.357941,1.015437,1.773351e+05,18.25177
min,0.0,1920.000000,1964.000000,11.000000,1.000000,2.500500e+04,1.00000
25%,0.0,1997.000000,2007.000000,93.000000,6.300000,3.958250e+04,46.00000
50%,0.0,2006.000000,2014.000000,105.000000,7.000000,6.774350e+04,59.00000
75%,0.0,2013.000000,2018.000000,119.000000,7.600000,1.400555e+05,72.00000
max,0.0,2020.000000,2021.000000,557.000000,9.500000,2.327795e+06,100.00000

## 5) Sort your dataframe on `runtimeMinutes`. What is the shortest and longest (use argument `ascending=False`) movie or tv series in this dataset?

In [73]:
#df.sort_values(by='runtimeMinutes', ascending=False)[['primaryTitle', 'runtimeMinutes']].head(1) -> 557 min
#df.sort_values(by='runtimeMinutes', ascending=True)[['primaryTitle', 'runtimeMinutes']].head(1) -> 11 min

## 6) In the answer to the question before we almost only saw tv-series. Sort on both `titleType` and `runtimeMinutes` to figure out what the longest movie is in this dataset.

In [74]:
df[df['titleType'] == 'movie'].sort_values(by='runtimeMinutes', ascending=False)[['primaryTitle', 'runtimeMinutes']]

                  primaryTitle  runtimeMinutes
4557        Gangs of Wasseypur           321.0
2834                 Red Cliff           288.0
1100                Gettysburg           271.0
1377                    Hamlet           242.0
5820         Leaving Neverland           240.0
...                        ...             ...
46                       Dumbo            64.0
3467  5 Centimeters Per Second            63.0
5375          Endless Corridor            52.0
4924       The Garden of Words            46.0
3                 Sherlock Jr.            45.0

[5252 rows x 2 columns]

## 7) Check which column has the most null values.

In [75]:
df.isnull().sum().sort_values(ascending=False)

endYear                 5395
genre3                  1767
opening_weekend_usa     1327
budget                  1260
gross_usa               1133
metascore               1014
cumulative_worldwide     799
tagline                  570
genre2                   449
primary_language          28
color                     21
country                   13
runtimeMinutes             3
startYear                  0
originalTitle              0
primaryTitle               0
tconst                     0
titleType                  0
genre1                     0
genres                     0
isAdult                    0
url                        0
numVotes                   0
averageRating              0
summary                    0
image_url                  0
dtype: int64

## 8) We are going to delete column `endYear`. Don't forget to assign it back to your variable df. Also check make sure that your df now has 25 columns instead of 26 columns.

In [76]:
#df = df.drop(columns='endYear').head(5)
#df.shape[1]
len(df.columns)

26

## 9) Create a new column called `new_rating` that multiplies column `averageRating` by 10 (so it is now on a scale of 1 to 100).

In [77]:
df['new_rating'] = df['averageRating'] * 10

## 10) Do a value counts to find out how many adult movies are in this dataset (use column `isAdult`)

In [78]:
(df['isAdult'] == 1).sum()

np.int64(0)