## Let's finally do some selections and find your favorite movies

## 1) import pandas, read in the movies dataset and make sure you see all the columns

https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv

In [2]:
import pandas as pd
df = pd.read_csv('https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv')
df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,...,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,...,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,...,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,...,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...
3,tt0015324,movie,Sherlock Jr.,Sherlock Jr.,0,1924,NaN,45.0,"Action,Comedy,Romance",Action,...,USA,NaN,Black and White,NaN,NaN,"$977,375",NaN,every inch of footage holds such a laugh!,"A film projectionist longs to be a detective, ...",https://m.media-amazon.com/images/M/MV5BZWFhOG...
4,tt0015648,movie,Battleship Potemkin,Bronenosets Potemkin,0,1925,NaN,75.0,"Drama,History,Thriller",Drama,...,Soviet Union,NaN,Black and White,NaN,"$5,641,","$51,198","$61,389",The Sensational Russian Film which is astoundi...,In the midst of the Russian Revolution of 1905...,https://m.media-amazon.com/images/M/MV5BMTEyMT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5825,tt9686708,movie,The King of Staten Island,The King of Staten Island,0,2020,NaN,136.0,"Comedy,Drama",Comedy,...,USA,English,Color,NaN,NaN,NaN,"$2,239,757",NaN,Scott has been a case of arrested development ...,https://m.media-amazon.com/images/M/MV5BYzkxMz...
5826,tt9698480,tvSeries,The Stranger,The Stranger,0,2020,2020.0,42.0,"Crime,Drama,Mystery",Crime,...,UK,English,Color,NaN,NaN,NaN,NaN,We All Have Secrets,Follows the lives of suburban families whose s...,https://m.media-amazon.com/images/M/MV5BNWNlYz...
5827,tt9777644,movie,Da 5 Bloods,Da 5 Bloods,0,2020,NaN,154.0,"Adventure,Drama,War",Adventure,...,USA,English,Color,NaN,NaN,NaN,NaN,NaN,Four African-American vets battle the forces o...,https://m.media-amazon.com/images/M/MV5BNjE4OD...
5828,tt9806192,movie,I Lost My Body,J'ai perdu mon corps,0,2019,NaN,81.0,"Animation,Drama,Fantasy",Animation,...,France,French,Color,NaN,NaN,NaN,"$1,136,431",An extraordinary journey in self-discovery.,"A story of Naoufel, a young man who is in love...",https://m.media-amazon.com/images/M/MV5BNDZjZj...
5829,tt9866072,movie,Holidate,Holidate,0,2020,NaN,103.0,"Comedy,Romance",Comedy,...,USA,English,Color,NaN,NaN,NaN,NaN,Who's Your Perfect Plus-One?,"Fed up with being single on holidays, two stra...",https://m.media-amazon.com/images/M/MV5BYWVmYT...

## 2) Create a new dataframe that only has columns `['titleType', 'originalTitle', 'startYear', 'genres', 'averageRating', 'primary_language', 'country']` of your dataframe and assign it to variable `df_new`.

In [5]:
df_new = df[['titleType', 'originalTitle', 'startYear', 'genres', 'averageRating', 'primary_language', 'country']]
df_new

,titleType,originalTitle,startYear,genres,averageRating,primary_language,country
0,movie,Das Cabinet des Dr. Caligari,1920,"Fantasy,Horror,Mystery",8.1,NaN,Germany
1,movie,The Kid,1921,"Comedy,Drama,Family",8.3,NaN,USA
2,movie,"Nosferatu, eine Symphonie des Grauens",1922,"Fantasy,Horror",7.9,NaN,Germany
3,movie,Sherlock Jr.,1924,"Action,Comedy,Romance",8.2,NaN,USA
4,movie,Bronenosets Potemkin,1925,"Drama,History,Thriller",8.0,NaN,Soviet Union
...,...,...,...,...,...,...,...
5825,movie,The King of Staten Island,2020,"Comedy,Drama",7.1,English,USA
5826,tvSeries,The Stranger,2020,"Crime,Drama,Mystery",7.3,English,UK
5827,movie,Da 5 Bloods,2020,"Adventure,Drama,War",6.5,English,USA
5828,movie,J'ai perdu mon corps,2019,"Animation,Drama,Fantasy",7.6,French,France
5829,movie,Holidate,2020,"Comedy,Romance",6.1,English,USA

## 3) Select all movies and tv series that have an average rating of 9.2 or higher. How many are there? Is your favorite movie or tv series in the list?

In [20]:
df_new[df_new['averageRating'] >= 9.2] #.count()

,titleType,originalTitle,startYear,genres,averageRating,primary_language,country
316,movie,The Godfather,1972,"Crime,Drama",9.2,English,USA
1214,movie,The Shawshank Redemption,1994,Drama,9.3,English,USA
1712,tvSeries,The Sopranos,1999,"Crime,Drama",9.2,English,USA
2036,movie,Hababam Sinifi,1975,"Comedy,Drama",9.3,Turkish,Turkey
2257,tvSeries,The Wire,2002,"Crime,Drama,Thriller",9.3,English,USA
2784,tvSeries,Avatar: The Last Airbender,2005,"Action,Adventure,Animation",9.2,English,USA
3397,tvSeries,Breaking Bad,2008,"Crime,Drama,Thriller",9.5,English,USA
3425,tvSeries,Game of Thrones,2011,"Action,Adventure,Drama",9.3,English,USA
3821,tvSeries,Scam 1992: The Harshad Mehta Story,2020,"Biography,Crime,Drama",9.4,Hindi,India
4842,tvSeries,Cosmos: A Spacetime Odyssey,2014,Documentary,9.3,English,USA
4926,movie,CM101MMXI Fundamentals,2013,"Comedy,Documentary",9.2,Turkish,Turkey
4997,tvSeries,Rick and Morty,2013,"Adventure,Animation,Comedy",9.2,English,USA
5312,tvSeries,The Filthy Frank Show,2011,"Comedy,Fantasy,Music",9.5,English,USA

## 4) Select all movies and tv series that have an average rating of 9.2 or higher AND sort them on start year. Which one ends up last?

In [24]:
df_new[df_new['averageRating'] >= 9.2].sort_values(by='startYear', ascending=False)

,titleType,originalTitle,startYear,genres,averageRating,primary_language,country
3821,tvSeries,Scam 1992: The Harshad Mehta Story,2020,"Biography,Crime,Drama",9.4,Hindi,India
4842,tvSeries,Cosmos: A Spacetime Odyssey,2014,Documentary,9.3,English,USA
4926,movie,CM101MMXI Fundamentals,2013,"Comedy,Documentary",9.2,Turkish,Turkey
4997,tvSeries,Rick and Morty,2013,"Adventure,Animation,Comedy",9.2,English,USA
3425,tvSeries,Game of Thrones,2011,"Action,Adventure,Drama",9.3,English,USA
5312,tvSeries,The Filthy Frank Show,2011,"Comedy,Fantasy,Music",9.5,English,USA
3397,tvSeries,Breaking Bad,2008,"Crime,Drama,Thriller",9.5,English,USA
2784,tvSeries,Avatar: The Last Airbender,2005,"Action,Adventure,Animation",9.2,English,USA
2257,tvSeries,The Wire,2002,"Crime,Drama,Thriller",9.3,English,USA
1712,tvSeries,The Sopranos,1999,"Crime,Drama",9.2,English,USA
1214,movie,The Shawshank Redemption,1994,Drama,9.3,English,USA
2036,movie,Hababam Sinifi,1975,"Comedy,Drama",9.3,Turkish,Turkey
316,movie,The Godfather,1972,"Crime,Drama",9.2,English,USA

## 5) Find your favorite movie or tv series in the list. What rating does it get? (use `.str.contains('your_text', case=False)`, see also the cheatsheet)

In [30]:
pd.options.display.max_columns = 50
df[df['primaryTitle'].str.contains('Altered Carbon', case=False, na=False)]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
4741,tt2261227,tvSeries,Altered Carbon,Altered Carbon,0,2018,2020.0,60.0,"Action,Drama,Sci-Fi",Action,Drama,Sci-Fi,https://www.imdb.com/title/tt2261227,8.0,140541,NaN,USA,English,Color,NaN,NaN,NaN,NaN,No body forgets.,Set in a future where consciousness is digitiz...,https://m.media-amazon.com/images/M/MV5BNjIxMW...

## 6) Find all movies (not tvSeries) that have a rating higher than 8.5 and are in English

In [40]:
df_new2 = df[
    (df['titleType'] == 'movie') &
     (df['averageRating'] > 8.5) &
      (df['primary_language'] == 'English')
     ] #25 movies

df_new2

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
65,tt0038650,movie,It's a Wonderful Life,It's a Wonderful Life,0,1946,NaN,130.0,"Drama,Family,Fantasy",Drama,Family,Fantasy,https://www.imdb.com/title/tt0038650,8.6,402576,89.0,USA,English,Black and White,"$3,180,000","$44,000,","$44,000","$6,184,298",Wonderful! Wonderful! Wonderful! How could ...,An angel is sent from Heaven to help a despera...,https://m.media-amazon.com/images/M/MV5BZjc4ND...
133,tt0050083,movie,12 Angry Men,12 Angry Men,0,1957,NaN,96.0,"Crime,Drama",Crime,Drama,NaN,https://www.imdb.com/title/tt0050083,9.0,685185,96.0,USA,English,Black and White,"$350,000",NaN,NaN,$576,They have twelve scraps of paper... Twelve cha...,A jury holdout attempts to prevent a miscarria...,https://m.media-amazon.com/images/M/MV5BMWU4N2...
316,tt0068646,movie,The Godfather,The Godfather,0,1972,NaN,175.0,"Crime,Drama",Crime,Drama,NaN,https://www.imdb.com/title/tt0068646,9.2,1608367,100.0,USA,English,Color,"$6,000,000","$302,393,","$134,966,411","$246,120,986",An offer you can't refuse.,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
354,tt0071562,movie,The Godfather: Part II,The Godfather: Part II,0,1974,NaN,202.0,"Crime,Drama",Crime,Drama,NaN,https://www.imdb.com/title/tt0071562,9.0,1122882,90.0,USA,English,Color,"$13,000,000","$171,417,","$47,834,595","$48,035,783",All the power on earth can't change destiny.,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
372,tt0073486,movie,One Flew Over the Cuckoo's Nest,One Flew Over the Cuckoo's Nest,0,1975,NaN,133.0,Drama,Drama,NaN,NaN,https://www.imdb.com/title/tt0073486,8.7,913193,83.0,USA,English,Color,"$3,000,000",NaN,"$108,981,275","$108,997,629","If he's crazy, what does that make you?",A criminal pleads insanity and is admitted to ...,https://m.media-amazon.com/images/M/MV5BZjA0OW...
406,tt0076759,movie,Star Wars: Episode IV - A New Hope,Star Wars,0,1977,NaN,121.0,"Action,Adventure,Fantasy",Action,Adventure,Fantasy,https://www.imdb.com/title/tt0076759,8.6,1225032,90.0,USA,English,Color,"$11,000,000","$1,554,475,","$460,998,507","$775,398,007",May the Force be with you. One year old today....,Luke Skywalker joins forces with a Jedi Knight...,https://m.media-amazon.com/images/M/MV5BNzVlY2...
465,tt0080684,movie,Star Wars: Episode V - The Empire Strikes Back,Star Wars: Episode V - The Empire Strikes Back,0,1980,NaN,124.0,"Action,Adventure,Fantasy",Action,Adventure,Fantasy,https://www.imdb.com/title/tt0080684,8.7,1152939,82.0,USA,English,Color,"$18,000,000","$4,910,483,","$292,753,960","$538,375,067",The Star Wars saga continues,After the Rebels are brutally overpowered by t...,https://m.media-amazon.com/images/M/MV5BYmU1ND...
913,tt0099685,movie,Goodfellas,Goodfellas,0,1990,NaN,146.0,"Biography,Crime,Drama",Biography,Crime,Drama,https://www.imdb.com/title/tt0099685,8.7,1013622,90.0,USA,English,Color,"$25,000,000","$6,368,901,","$46,836,214","$46,952,991",Murderers come with smiles.,The story of Henry Hill and his life in the mo...,https://m.media-amazon.com/images/M/MV5BY2NkZj...
993,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,NaN,118.0,"Crime,Drama,Thriller",Crime,Drama,Thriller,https://www.imdb.com/title/tt0102926,8.6,1262558,85.0,USA,English,Color,"$19,000,000","$13,766,814,","$130,742,922","$272,742,922",From the terrifying best seller,A young F.B.I. cadet must receive the help of ...,https://m.media-amazon.com/images/M/MV5BNjNhZT...
1136,tt0108052,movie,Schindler's List,Schindler's List,0,1993,NaN,195.0,"Biography,Drama,History",Biography,Drama,History,https://www.imdb.com/title/tt0108052,8.9,1206843,94.0,USA,English,Black and White,"$22,000,000","$656,636,","$96,898,818","$322,161,245",The List Is Life.,"In German-occupied Poland during World War II,...",https://m.media-amazon.com/images/M/MV5BNDE4OT...
1178,tt0109830,movie,Forrest Gump,Forrest Gump,0,1994,NaN,142.0,"Drama,Romance",Drama,Romance,NaN,https://www.imdb.com/title/tt0109830,8.8,1796488,82.0,USA,English,Black and White,"$55,000,000","$24,450,602,","$330,455,270","$678,226,133",Life is like a box of chocolates...you never k...,"The presidencies of Kennedy and Johnson, the e...",https://m.media-amazon.com/images/M/MV5BNWIwOD...
1206,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,NaN,154.0,"Crime,Drama",Crime,Drama,NaN,https://www.imdb.com/title/tt0110912,8.9,1815539,94.0,USA,English,Color,"$8,000,000","$9,311,882,","$107,928,762","$213,928,762",Girls like me don't make invitations like this...,"The lives of two mob hitmen, a boxer, a gangst...",https://m.media-amazon.com/images/M/MV5BNGNhMD...
1214,tt0111161,movie,The Shawshank Redemption,The Shawshank Redemption,0,1994,NaN,142.0,Drama,Drama,NaN,NaN,https://www.imdb.com/title/tt0111161,9.3,2327795,80.0,USA,English,Color,"$25,000,000","$727,327,","$28,699,976","$28,817,291",Fear can hold you prisoner. Hope can set you f...,Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1309,tt0114369,movie,Se7en,Se7en,0,1995,NaN,127.0,"Crime,Drama,Mystery",Crime,Drama,Mystery,https://www.imdb.com/title/tt0114369,8.6,1435130,65.0,USA,English,Color,"$33,000,000","$13,949,807,","$100,125,643","$327,333,559","Long is the way, and hard, that out of hell le...","Two detectives, a rookie and a veteran, hunt a...",https://m.media-amazon.com/images/M/MV5BOTUwOD...
1582,tt0120689,movie,The Green Mile,The Green Mile,0,1999,NaN,189.0,"Crime,Drama,Fantasy",Crime,Drama,Fantasy,https://www.imdb.com/title/tt0120689,8.6,1139715,61.0,USA,English,Color,"$60,000,000","$18,017,152,","$136,801,374","$286,801,374",Miracles happen in the most unexpected places.,The lives of guards on Death Row are affected ...,https://m.media-amazon.com/images/M/MV5BMTUxMz...
1588,tt0120737,movie,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,0,2001,NaN,178.0,"Action,Adventure,Drama",Action,Adventure,Drama,https://www.imdb.com/title/tt0120737,8.8,1650590,92.0,New Zealand,English,Color,"$93,000,000","$47,211,490,","$315,544,750","$888,159,092","One ring to rule them all, One ring to find th...",A meek Hobbit from the Shire and eight compani...,https://m.media-amazon.com/images/M/MV5BN2EyZj...
1609,tt0120815,movie,Saving Private Ryan,Saving Private Ryan,0,1998,NaN,169.0,"Drama,War",Drama,War,NaN,https://www.imdb.com/title/tt0120815,8.6,1228304,91.0,USA,English,Color,"$70,000,000","$30,576,104,","$217,049,603","$482,349,603","There was only one man left in the family, and...","Following the Normandy Landings, a group of U....",https://m.media-amazon.com/images/M/MV5BZjhkMD...
1678,tt0133093,movie,The Matrix,The Matrix,0,1999,NaN,136.0,"Action,Sci-Fi",Action,Sci-Fi,NaN,https://www.imdb.com/title/tt0133093,8.7,1666122,73.0,USA,English,Color,"$63,000,000","$27,788,331,","$171,479,930","$466,364,682","Unfortunately, no one can be told what the Mat...",When a beautiful stranger leads computer hacke...,https://m.media-amazon.com/images/M/MV5BNzQzOT...
1692,tt0137523,movie,Fight Club,Fight Club,0,1999,NaN,139.0,Drama,Drama,NaN,NaN,https://www.imdb.com/title/tt0137523,8.8,1843665,66.0,USA,English,Color,"$63,000,000","$11,035,485,","$37,030,102","$101,209,593",Losing all hope is freedom,An insomniac office worker and a devil-may-car...,https://m.media-amazon.com/images/M/MV5BMmEzNT...
1795,tt0167260,movie,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,0,2003,NaN,201.0,"Action,Adventure,Drama",Action,Adventure,Drama,https://www.imdb.com/title/tt0167260,8.9,1633789,94.0,New Zealand,English,Color,"$94,000,000","$72,629,713,","$377,845,905","$1,142,456,987",The eye of the enemy is moving.,Gandalf and Aragorn lead the World of Men agai...,https://m.media-amazon.com/images/M/MV5BNzA5ZD...
1796,tt0167261,movie,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers,0,2002,NaN,179.0,"Action,Adventure,Drama",Action,Adventure,Drama,https://www.imdb.com/title/tt0167261,8.7,1477173,87.0,New Zealand,English,Color,"$94,000,000","$62,007,528,","$342,551,365","$943,396,133",The Journey Continues December 18th,While Frodo and Sam edge closer to Mordor with...,https://m.media-amazon.com/images/M/MV5BZGMxZT...
3056,tt0468569,movie,The Dark Knight,The Dark Knight,0,2008,NaN,152.0,"Action,Crime,Drama",Action,Crime,Drama,https://www.imdb.com/title/tt0468569,9.0,2289496,84.0,USA,English,Color,"$185,000,000","$158,411,483,","$534,858,444","$1,005,973,645",I Believe In Harvey Dent.,When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3294,tt0816692,movie,Interstellar,Interstellar,0,2014,NaN,169.0,"Adventure,Drama,Sci-Fi",Adventure,Drama,Sci-Fi,https://www.imdb.com/title/tt0816692,8.6,1498143,74.0,USA,English,Color,"$165,000,000","$47,510,360,","$188,020,017","$701,795,571",The end of Earth will not be the end of us.,A team of explorers travel through a wormhole ...,https://m.media-amazon.com/images/M/MV5BZjdkOT...
3973,tt1375666,movie,Inception,Inception,0,2010,NaN,148.0,"Action,Adventure,Sci-Fi",Action,Adventure,Sci-Fi,https://www.imdb.com/title/tt1375666,8.8,2053175,74.0,USA,English,Color,"$160,000,000","$62,785,337,","$292,576,195","$836,836,967",Your mind is the scene of the crime,A thief who steals corporate secrets through t...,https://m.media-amazon.com/images/M/MV5BMjAxMz...
5783,tt8503618,movie,Hamilton,Hamilton,0,2020,NaN,160.0,"Biography,Drama,History",Biography,Drama,History,https://www.imdb.com/title/tt8503618,8.6,51947,90.0,USA,English,Color,NaN,NaN,NaN,NaN,Experience the Original Broadway Production,The real life of one of America's foremost fou...,https://m.media-amazon.com/images/M/MV5BNjViNW...

## 7) Filter you dataset on all movies from Netherlands or Belgium. What is the highest rated movie in the list?
#### Hints:
- you can try filtering using method `.isin(['Netherlands', 'Belgium'])`

In [46]:
df_NLBE = df[
    (df['titleType'] == 'movie') &
    (df['country'].isin(['Netherlands', 'Belgium']))
].sort_values(by='averageRating', ascending=False)

df_NLBE

#Mr.Nobody

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
3130,tt0485947,movie,Mr. Nobody,Mr. Nobody,0,2009,NaN,141.0,"Drama,Fantasy,Romance",Drama,Fantasy,Romance,https://www.imdb.com/title/tt0485947,7.8,215398,63.0,Belgium,English,Color,"$47,000,000","$1,612,","$3,622","$3,559,160","Nothing is real, everything is possible.",A boy stands on a station platform as a train ...,https://m.media-amazon.com/images/M/MV5BMTg4OD...
813,tt0096163,movie,The Vanishing,Spoorloos,0,1988,NaN,107.0,"Mystery,Thriller",Mystery,Thriller,NaN,https://www.imdb.com/title/tt0096163,7.7,33790,NaN,Netherlands,Dutch,Color,NaN,NaN,NaN,NaN,NaN,"Rex and Saskia, a young couple in love, are on...",https://m.media-amazon.com/images/M/MV5BNzczMW...
4606,tt2024519,movie,The Broken Circle Breakdown,The Broken Circle Breakdown,0,2012,NaN,111.0,"Drama,Music,Romance",Drama,Music,Romance,https://www.imdb.com/title/tt2024519,7.7,39238,70.0,Belgium,Flemish,Color,NaN,"$7,100,","$175,058","$5,990,754",Sometimes love can conquer fate. Sometimes not.,"Elise and Didier fall in love at first sight, ...",https://m.media-amazon.com/images/M/MV5BMTQzMz...
2656,tt0389557,movie,Black Book,Zwartboek,0,2006,NaN,145.0,"Drama,Thriller,War",Drama,Thriller,War,https://www.imdb.com/title/tt0389557,7.7,72428,71.0,Netherlands,Dutch,Color,"$21,000,000","$112,521,","$4,398,532","$26,768,563","To fight the enemy, she must become one of them.",In the Nazi-occupied Netherlands during World ...,https://m.media-amazon.com/images/M/MV5BODFlNT...
839,tt0097108,movie,"The Cook, the Thief, His Wife & Her Lover","The Cook, the Thief, His Wife & Her Lover",0,1989,NaN,124.0,"Crime,Drama",Crime,Drama,NaN,https://www.imdb.com/title/tt0097108,7.6,34783,62.0,Netherlands,English,Color,NaN,"$252,223,","$7,724,701","$7,724,701",Greenaway's recipe of food and sex mixed with ...,"At Le Hollandais gourmet restaurant, every nig...",https://m.media-amazon.com/images/M/MV5BZTlmM2...
1015,tt0103905,movie,Man Bites Dog,C'est arrivé près de chez vous,0,1992,NaN,95.0,"Comedy,Crime,Drama",Comedy,Crime,Drama,https://www.imdb.com/title/tt0103905,7.5,36156,67.0,Belgium,French,Black and White,"BEF1,000,000","$15,176,","$205,569","$205,569",A Killer Comedy,A film crew follows a ruthless thief and heart...,https://m.media-amazon.com/images/M/MV5BMWQzYj...
4465,tt1827512,movie,The Kid with a Bike,Le gamin au vélo,0,2011,NaN,87.0,"Drama,Family",Drama,Family,NaN,https://www.imdb.com/title/tt1827512,7.4,26283,87.0,Belgium,French,Color,NaN,"$45,933,","$1,470,000","$7,011,798",NaN,"Abandoned by his father, a young boy is left i...",https://m.media-amazon.com/images/M/MV5BMTQ3OT...
4970,tt2737050,movie,"Two Days, One Night","Deux jours, une nuit",0,2014,NaN,95.0,Drama,Drama,NaN,NaN,https://www.imdb.com/title/tt2737050,7.3,45056,89.0,Belgium,French,Color,"EUR7,000,000","$30,700,","$1,436,243","$9,016,922",NaN,"Liège, Belgium. Sandra is a factory worker who...",https://m.media-amazon.com/images/M/MV5BMjIyMz...
3807,tt1232776,movie,Fish Tank,Fish Tank,0,2009,NaN,123.0,Drama,Drama,NaN,NaN,https://www.imdb.com/title/tt1232776,7.3,58738,81.0,Netherlands,English,Color,"$3,000,000","$25,854,","$374,675","$2,404,300","Live, love and give as good as you get.",Everything changes for 15-year-old Mia when he...,https://m.media-amazon.com/images/M/MV5BMTc1NT...
3859,tt1270262,movie,The Devil's Double,The Devil's Double,0,2011,NaN,109.0,"Biography,Drama,Thriller",Biography,Drama,Thriller,https://www.imdb.com/title/tt1270262,7.1,60081,52.0,Belgium,English,Color,"$19,100,000","$96,414,","$1,361,512","$5,728,213",Play the part or suffer the consequences,A chilling vision of the House of Saddam Husse...,https://m.media-amazon.com/images/M/MV5BMjI2Mj...
5231,tt3792960,movie,The Brand New Testament,Le tout nouveau testament,0,2015,NaN,114.0,"Comedy,Fantasy",Comedy,Fantasy,NaN,https://www.imdb.com/title/tt3792960,7.1,29653,70.0,Belgium,French,Color,"EUR8,555,500","$10,422,","$127,910","$15,709,652",God exists. He lives in Brussels with his teen...,Did you know that God is alive and lives in Br...,https://m.media-amazon.com/images/M/MV5BMjM3OT...
4518,tt1895315,movie,Brimstone,Brimstone,0,2016,NaN,148.0,"Drama,Mystery,Thriller",Drama,Mystery,Thriller,https://www.imdb.com/title/tt1895315,7.1,36303,45.0,Netherlands,English,Color,"EUR12,000,000",NaN,NaN,"$2,140,941",Retribution is coming,From the moment the new reverend climbs the pu...,https://m.media-amazon.com/images/M/MV5BNGU0Y2...
3649,tt1130988,movie,JCVD,JCVD,0,2008,NaN,97.0,"Action,Comedy,Crime",Action,Comedy,Crime,https://www.imdb.com/title/tt1130988,7.1,37417,64.0,Belgium,French,Color,"EUR10,000,000","$20,119,","$470,691","$2,342,211",Be Aware,Jean-Claude Van Damme gets involved in a bank ...,https://m.media-amazon.com/images/M/MV5BNDAwMD...
2222,tt0297284,movie,Mindhunters,Mindhunters,0,2004,NaN,106.0,"Crime,Horror,Thriller",Crime,Horror,Thriller,https://www.imdb.com/title/tt0297284,6.4,57837,33.0,Netherlands,English,Color,"$27,000,000","$2,000,000,","$4,480,744","$21,148,829","For seven elite profilers, finding a serial ki...",Trainees in the FBI's psychological profiling ...,https://m.media-amazon.com/images/M/MV5BMTAwOT...
4795,tt2343793,movie,Third Person,Third Person,0,2013,NaN,137.0,"Drama,Romance",Drama,Romance,NaN,https://www.imdb.com/title/tt2343793,6.3,26688,38.0,Belgium,English,Color,"$28,000,000","$38,856,","$1,021,398","$2,624,761",Watch Me.,Three interlocking love stories involving thre...,https://m.media-amazon.com/images/M/MV5BMjAwNT...
4490,tt1850397,movie,The Loft,The Loft,0,2014,NaN,108.0,"Mystery,Romance,Thriller",Mystery,Romance,Thriller,https://www.imdb.com/title/tt1850397,6.3,51850,24.0,Belgium,English,Color,"$14,000,000","$2,747,342,","$6,002,684","$11,020,402",Five friends. Five keys. The right place to do...,Five married guys secretly share a penthouse l...,https://m.media-amazon.com/images/M/MV5BMjAyNT...
4089,tt1467304,movie,The Human Centipede (First Sequence),The Human Centipede (First Sequence),0,2009,NaN,92.0,Horror,Horror,NaN,NaN,https://www.imdb.com/title/tt1467304,4.4,72948,33.0,Netherlands,English,Color,"EUR1,500,000","$12,424,","$181,467","$325,113",100% medically accurate.,A mad scientist kidnaps and mutilates a trio o...,https://m.media-amazon.com/images/M/MV5BMTY4Nz...
4150,tt1530509,movie,The Human Centipede II (Full Sequence),The Human Centipede II (Full Sequence),0,2011,NaN,91.0,"Crime,Horror",Crime,Horror,NaN,https://www.imdb.com/title/tt1530509,3.8,35636,17.0,Netherlands,English,Black and White,NaN,"$49,456,","$141,877","$170,323",Sick.,"Inspired by the fictional Dr. Heiter, disturbe...",https://m.media-amazon.com/images/M/MV5BMjkwMD...