# Let's make some plots of the movie dataset

## For which movies / tv series do critics and normal users differ in their opinion?

## 1) Import pandas, plotly.express as px, read in the movies dataset and change some pandas settings to show all columns (and if needed check out the first couple of lines to see your dataframe)

In [2]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv')
df.head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,...,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,...,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,...,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,...,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...

## 2) Create a subset of your data by only selecting movies and assign it to variable `df_movies`

In [6]:
df_movies = df[df['titleType'] == 'movie']
#df_movies.tail(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,...,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
5827,tt9777644,movie,Da 5 Bloods,Da 5 Bloods,0,2020,NaN,154.0,"Adventure,Drama,War",Adventure,...,USA,English,Color,NaN,NaN,NaN,NaN,NaN,Four African-American vets battle the forces o...,https://m.media-amazon.com/images/M/MV5BNjE4OD...
5828,tt9806192,movie,I Lost My Body,J'ai perdu mon corps,0,2019,NaN,81.0,"Animation,Drama,Fantasy",Animation,...,France,French,Color,NaN,NaN,NaN,"$1,136,431",An extraordinary journey in self-discovery.,"A story of Naoufel, a young man who is in love...",https://m.media-amazon.com/images/M/MV5BNDZjZj...
5829,tt9866072,movie,Holidate,Holidate,0,2020,NaN,103.0,"Comedy,Romance",Comedy,...,USA,English,Color,NaN,NaN,NaN,NaN,Who's Your Perfect Plus-One?,"Fed up with being single on holidays, two stra...",https://m.media-amazon.com/images/M/MV5BYWVmYT...

## 3) Use `.value_counts()` on `startYear` and assign that count to a variable called `df_startyear_count`

In [8]:
df_startyear_count = df['startYear'].value_counts()
#df_startyear_count.head(3)

startYear
2013    252
2014    247
2011    241
Name: count, dtype: int64

## 4) Create a nice bar plot with plotly.express and find out which year has the most movies in this dataset

In [16]:
px.bar(
    data_frame= df_startyear_count
)

#2013

## 5) Create a scatter plot of `metascore` on the x-axis and `averageRating` on the y-axis
### (metascore is what critics think of the movies, average rating is what users or ordinary viewers think)

In [18]:
px.scatter(
    data_frame = df_movies,
    x='metascore',
    y='averageRating',
    hover_data= 'primaryTitle'
)

## 6) Create the same plot as in 5) but add `hover_data=['primaryTitle']` to find out which title is represented by a dot.<br>Find examples of outliers where the critics think it's a bad movie and the users find it a good movie.

In [ ]:
#Elite Squad

## 7) Use the same plot as in 6) and now give the scatters the color based on column `color`. When you try this, you probably will first get an error, because (apparently) NaN values are not allowed by plotly when doing this. So you will have to fill the na's with a string value to fix this.

In [19]:
px.scatter(
    data_frame = df_movies,
    x='metascore',
    y='averageRating',
    hover_data= 'primaryTitle',
    color= 'color'
)

## 8) You can play with the chart above and turn off scatters by clicking on the legend. Try removing color named 'Color' from the legend. You can also zoom etc.

In [20]:
px.scatter(
    data_frame = df_movies,
    x='metascore',
    y='averageRating',
    hover_data= 'primaryTitle',
    color= 'color'
)

## 9) Now for the ultimate chart: filter your dataframe so that you only have countries `Germany` and `USA` and use the same code as in 7) and also use argument `facet_row` with column `country` and see what happens :)<br>

In [22]:
px.scatter(
    data_frame = df_movies[df_movies['country'].isin(['Germany', 'USA'])],
    x='metascore',
    y='averageRating',
    hover_data= 'primaryTitle',
    color= 'color',
    facet_row= 'country'
)

## 10) Create a bar plot of the rating of the top 5 highest rated black and white movies

In [26]:
px.bar(
    data_frame= df_movies[df_movies['color'] == 'Black and White'].sort_values(by= 'averageRating', ascending=False).head(5),
    x='primaryTitle',
    y='averageRating',
    hover_data= 'primaryTitle',
)